[project]
name = "simple_api"
readme = "README.md"
version = "0.0.1"
description = "A simple REST api for teachers, students, and classes built using Django Ninja."
requires-python = ">=3.13"
dependencies = [
    "django~=5.1",
    "djangorestframework>=3.15.2",
]

[dependency-groups]
dev = [
    "ipython~=9.0",
    "django-types~=0.20",
]

[tool.ruff]
line-length = 119
