# Generated by Django 5.1.7 on 2025-03-06 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, unique=True)),
                ("phone", models.CharField(max_length=64)),
            ],
            options={
                "verbose_name": "People",
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, unique=True)),
                ("maximum_capacity", models.PositiveIntegerField(default=30)),
                ("students", models.ManyToManyField(related_name="classes_attending", to="simple_api.person")),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes_teaching",
                        to="simple_api.person",
                    ),
                ),
            ],
        ),
    ]
