# Generated by Django 5.1.7 on 2025-03-07 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simple_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="class",
            options={"verbose_name_plural": "Classes"},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name_plural": "People"},
        ),
    ]
